/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurpriseRouteImport } from './routes/surprise'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DishIdRouteImport } from './routes/dish.$id'

const SurpriseRoute = SurpriseRouteImport.update({
  id: '/surprise',
  path: '/surprise',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DishIdRoute = DishIdRouteImport.update({
  id: '/dish/$id',
  path: '/dish/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/pantry': typeof PantryRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/surprise': typeof SurpriseRoute
  '/dish/$id': typeof DishIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/pantry': typeof PantryRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/surprise': typeof SurpriseRoute
  '/dish/$id': typeof DishIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/pantry': typeof PantryRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/surprise': typeof SurpriseRoute
  '/dish/$id': typeof DishIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/pantry'
    | '/profile'
    | '/search'
    | '/surprise'
    | '/dish/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/pantry'
    | '/profile'
    | '/search'
    | '/surprise'
    | '/dish/$id'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/pantry'
    | '/profile'
    | '/search'
    | '/surprise'
    | '/dish/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  PantryRoute: typeof PantryRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SurpriseRoute: typeof SurpriseRoute
  DishIdRoute: typeof DishIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surprise': {
      id: '/surprise'
      path: '/surprise'
      fullPath: '/surprise'
      preLoaderRoute: typeof SurpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dish/$id': {
      id: '/dish/$id'
      path: '/dish/$id'
      fullPath: '/dish/$id'
      preLoaderRoute: typeof DishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  PantryRoute: PantryRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SurpriseRoute: SurpriseRoute,
  DishIdRoute: DishIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
